traits:
  Ruby: true

include:
  - cider-ci/task_components/database/configure.yml
  - cider-ci/task_components/database/delete.yml

scripts:

  create-database:
    body: |
      #!/usr/bin/env bash
      set -eux
      if [ -d legacy ]; then cd legacy; fi
      createdb "$DATABASE"
      psql -d "$DATABASE" -f db/structure.sql

  test:
    start_when:
      database has been created:
        script_key: create-database
      database has been configured:
        script_key: configure-database
