inherit_from:
  - '../../.rubocop.yml'
  # TODOs from rubocop upgrade:
  - '../../.rubocop_todo_procurement.yml'

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'features/**/*'
    - 'lib/tasks/procurement_tasks.rake'
    - 'node_modules/**/*'
    - 'spec/features/**/*'
    - 'test/**/*'
    - 'tmp/**/*'

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 128

Metrics/CyclomaticComplexity:
  Max: 10

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 11
