environment_variables:
  DATABASE: "leihs_test_{{CIDER_CI_TRIAL_ID}}"

scripts:
  configure-database:
    body: |
      #!/usr/bin/env ruby
      Dir.chdir ( Dir.exists?("legacy") ? "legacy" : "." ) do
        require 'yaml'
        db_config = {
          'adapter' => 'postgresql',
          'encoding' => 'unicode',
          'host' => 'localhost',
          'pool' => 20,
          'timeout' => 20,
          'username' => ENV['PGUSER'],
          'password' =>  ENV['PGPASSWORD'],
          'database' => ENV['DATABASE']}
        config = { ENV['RAILS_ENV'] => db_config}
        File.open('config/database.yml','w') { |file| file.write config.to_yaml }
      end
