jobs:

  borrow-scenarios:

    name: 'Borrow: Scenarios'

    description: |
      Run Borrow scenarios under MRI

    run_when:
      meta checks have passed:
        type: job
        job_key: meta
        states: [passed]


    context:

      task_defaults:
        load: 1.5
        max_trials: 3
        include:
          - cider-ci/task-components/database.yml

      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/tasks/borrow-scenarios.yml
