jobs:

  borrow-rspec-flapping-scenarios:

    name: 'Borrow: Rspec Flapping Scenarios'

    description: |
      Run Borrow rspec flapping scenarios under MRI

    run_when:
      meta checks have passed:
        type: job
        job_key: meta
        states: [passed]

    context:
      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/shared/flapping-context-configuration.yml
        - cider-ci/tasks/borrow-rspec-flapping-scenarios.yml
