jobs:

  borrow-rspec-flapping-scenarios:

    name: 'Borrow: Rspec Flapping Scenarios'

    description: |
      Run Borrow rspec flapping scenarios under MRI

    run_when:
      branch name matches master or borrow:
        type: branch
        include_match: '^.*(master|borrow).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:
      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/shared/flapping-context-configuration.yml
        - cider-ci/tasks/borrow-rspec-flapping-scenarios.yml
