jobs:

  borrow-rspec-scenarios:

    name: 'Borrow: Rspec Scenarios'

    description: |
      Run Borrow rspec scenarios under MRI

    run_when:
      branch name matches master or borrow:
        type: branch
        include_match: '^.*(next|master|borrow).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        load: 1.5
        max_trials: 3
        include:
          - cider-ci/task-components/database.yml

      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/tasks/borrow-rspec-scenarios.yml
