jobs:

  borrow-flapping-scenarios:

    name: 'Borrow: Flapping Scenarios'

    description: |
      Run Borrow flapping scenarios

    run_when:
      meta checks have passed:
        type: job
        job_key: meta
        states: [passed]


    context:
      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/shared/flapping-context-configuration.yml
        - cider-ci/tasks/borrow-flapping-scenarios.yml
