jobs:

  borrow-broken-scenarios:

    name: 'Borrow: Broken Scenarios'

    description: |
      Run Borrow broken scenarios

    context:

      task_defaults:
        load: 1.5
        max_trials: 2
        eager_trials: 1
        include:
          - cider-ci/task-components/database.yml

      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/tasks/borrow-broken-scenarios.yml
