jobs:
  borrow-manage-code-checks:

    name: 'Borrow/Manage: Code Checks'

    description: 'Run static checks and metrics: complexity, duplication, code format'

    run_when:
      branch name matches master or manage or borrow:
        type: branch
        include_match: '^.*(next|master|borrow|manage).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:
      include: cider-ci/shared/main-context.yml

      tasks:
        lint-ruby:
          name: Lint/Stylecheck with Rubocop
          scripts:
            test:
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                bundle exec rubocop
