jobs:
  leihs-admin-code-checks:

    name: 'Admin: Code Checks'

    description: 'Run static checks and metrics: complexity, duplication, code format'

    run_when:
      branch name matches master or admin:
        type: branch
        include_match: '^.*(next|master|admin).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:
      include: cider-ci/shared/main-context.yml

      tasks:
        lint-ruby:
          name: Lint/Stylecheck with Rubocop
          scripts:
            test:
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                bundle exec rubocop engines/leihs_admin/ -c engines/leihs_admin/.rubocop.yml
