jobs:

  leihs-admin-scenarios:

    name: 'Admin: Scenarios'

    description: |
      Run Admin engine scenarios under MRI

    run_when:
      branch name matches master or admin:
        type: branch
        include_match: '^.*(master|admin).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        max_trials: 3
        include:
          - cider-ci/task-components/database.yml

      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/tasks/leihs_admin-scenarios.yml
