jobs:

  manage_rspec_scenarios:

    name: 'Manage: Rspec Scenarios'

    description: |
      Run manage rspec scenarios under MRI

    run_when:
      branch name matches master or manage:
        type: branch
        include_match: '^.*(master|manage).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        load: 1.5
        max_trials: 3
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/manage_rspec_scenarios.yml
