jobs:

  manage-flapping-scenarios:

    name: 'Manage: Flapping Scenarios'

    description: |
      Run Manage flapping scenarios

    run_when:
      meta checks have passed:
        type: job
        job_key: meta
        states: [passed]


    context:
      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/shared/flapping-context-configuration.yml
        - cider-ci/tasks/manage-flapping-scenarios.yml
