jobs:

  manage-flapping-scenarios:

    name: 'Manage: Flapping Scenarios'

    description: |
      Run Manage flapping scenarios

    run_when:
      branch name matches master or manage:
        type: branch
        include_match: '^.*(master|manage).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:
      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/shared/flapping-context-configuration.yml
        - cider-ci/tasks/manage-flapping-scenarios.yml
