jobs:

  manage-rspec-flapping-scenarios:

    name: 'Manage: Rspec Flapping Scenarios'

    description: |
      Run manage rspec flapping scenarios under MRI

    run_when:
      meta checks have passed:
        type: job
        job_key: meta
        states: [passed]


    context:
      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/shared/flapping-context-configuration.yml
        - cider-ci/tasks/manage-rspec-flapping-scenarios.yml
