jobs:

  meta:

    name: Meta
    description: |
      Various superordinate quality assurance tasks

    run_when:
      always:
        type: branch
        include_match: '^.*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:
      task_defaults:
        max_trials: 1
        traits:
          Ruby: true

      tasks:
        git-branch-current:
          name: "Git tree contains latest commit from origin/master"
          scripts:
            main:
              body: |
                #!/usr/bin/env bash
                set -exu
                git fetch --all
                #
                # check if your tree still contains the current commit from master
                git rev-list --children HEAD | grep -q "$(git rev-parse origin/master)"

        scenario tasks are up-to-date:
          name: "Scenario tasks are up-to-date"
          scripts:
            main:
              body: |
                #!/usr/bin/env bash
                set -exu
                ./cider-ci/bin/create-scenario-tasks.rb
                test -z "$(git status --porcelain cider-ci/tasks)"

        assets compiled if changed:
          name: "Assets have been compiled if changed"
          scripts:
            test:
              body:
                read_and_replace_with: cider-ci/bin/check-assets-are-compiled

        "rails bug 25198 is open":
          name: "Check if Rails bug 25198 is still open. If it isn't we have to fix our code."
          scripts:
            test:
              body:
                read_and_replace_with: cider-ci/bin/check-rails-bug-25198.rb

        backend and frontend locales are synchronised:
          name: "Backend and frontend locales are synchronised"
          scripts:
            test:
              body:
                read_and_replace_with: cider-ci/bin/check-locales-are-synchronised

        extract missing and fuzzy translations:
          name: "Extract missing and fuzzy translations"
          tree_attachments:
            translation-todos:
              include_match: tmp\/translation-todos\/.*\.po$
              content_type: text/plain
          scripts:
            test:
              body:
                read_and_replace_with: bin/translation-todos

      include:
        - path: cider-ci/context-components/merged-submodules-check.yml
