jobs:
  procurement-code-checks:

    name: 'Procurement: Code Checks'

    description: 'Run static checks and metrics: complexity, duplication, code format'

    run_when:
      branch name matches master or procurement:
        type: branch
        include_match: '^.*(master|procurement).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:
      include: cider-ci/shared/main-context.yml

      tasks:
        lint-ruby:
          name: Lint/Stylecheck with Rubocop
          scripts:
            test:
              body: |
                set -eux
                export PATH=~/.rubies/$RUBY/bin:$PATH
                bundle exec rubocop engines/procurement/ -c engines/procurement/.rubocop.yml
