jobs:

  procurement-flapping-scenarios:

    name: 'Procurement: Flapping Scenarios'

    description: |
      Run procurement flapping scenarios

    run_when:
      branch name matches master or procurement:
        type: branch
        include_match: '^.*(next|master|procurement).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:
      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/shared/flapping-context-configuration.yml
        - cider-ci/tasks/procurement-flapping-scenarios.yml
