jobs:

  procurement-scenarios:

    name: 'Procurement: Scenarios'

    description: |
      Run Procurement engine scenarios under MRI

    run_when:
      branch name matches master or procurement:
        type: branch
        include_match: '^.*(master|procurement).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        max_trials: 3
        include:
          - cider-ci/task-components/database.yml

      include:
        - cider-ci/shared/main-context.yml
        - cider-ci/tasks/procurement-scenarios.yml
