jobs:

  rails-warnings-check:

    name: 'Rails warnings check'

    description: |
      Check if rails outputs something to STDERR (warnings, etc.)

    run_when:
      branch name matches master:
        type: branch
        include_match: '^.*master.*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      include:
        - cider-ci/shared/main-context.yml

      task_defaults:
        include:
          - cider-ci/task-components/database.yml

      tasks:
        count-stderr-lines:
          max_trials: 2
          name: 'Count if number of STDERR lines greater than 0'
          scripts:
            test:
              body: cider-ci/bin/check-rails-warnings.rb
